# Imports
import turtle
from datetime import date

currentYear = date.today().year
mr_turtle = turtle.Turtle()
mr_turtle.speed(2)

def square():
  mr_turtle.fillcolor("sandybrown")
  mr_turtle.begin_fill()
  mr_turtle.forward(100)
  mr_turtle.right(45)
  mr_turtle.forward(25)
  mr_turtle.right(45)
  mr_turtle.forward(25)
  mr_turtle.right(45)
  mr_turtle.forward(25)
  mr_turtle.right(45)
  mr_turtle.forward(100)
  mr_turtle.right(45)
  mr_turtle.forward(25)
  mr_turtle.right(45)
  mr_turtle.forward(25)
  mr_turtle.right(45)
  mr_turtle.forward(25)
  mr_turtle.right(45)
  mr_turtle.forward(50)
  mr_turtle.left(90)
  mr_turtle.forward(25)
  mr_turtle.right(90)
  mr_turtle.forward(75)
  mr_turtle.right(135)
  mr_turtle.forward(35)
  mr_turtle.left(180)
  mr_turtle.forward(35)  
  mr_turtle.right(90)
  mr_turtle.forward(25)
  mr_turtle.right(45)
  mr_turtle.forward(37.5)
  mr_turtle.right(90)
  mr_turtle.forward(25)
  mr_turtle.left(180)      
  mr_turtle.forward(25) 
  mr_turtle.right(90)
  mr_turtle.forward(37.5)
  mr_turtle.right(45)
  mr_turtle.forward(25)
  mr_turtle.right(90)
  mr_turtle.forward(35)
  mr_turtle.left(180)
  mr_turtle.forward(35)
  mr_turtle.right(135) 
  mr_turtle.forward(75)
  mr_turtle.right(90)
  mr_turtle.forward(25)
  mr_turtle.left(180)
  mr_turtle.forward(25)             
  mr_turtle.right(90)
  mr_turtle.forward(75)
  mr_turtle.right(135)
  mr_turtle.forward(35)
  mr_turtle.left(180)
  mr_turtle.forward(35)
  mr_turtle.right(90)
  mr_turtle.forward(25)
  mr_turtle.right(45)
  mr_turtle.forward(37.5)
  mr_turtle.right(90)
  mr_turtle.forward(25)
  mr_turtle.left(180)
  mr_turtle.forward(25)
  mr_turtle.right(90)
  mr_turtle.forward(37.5)
  mr_turtle.right(45)
  mr_turtle.forward(25)
  mr_turtle.right(90)
  mr_turtle.forward(35)
  mr_turtle.left(180)
  mr_turtle.forward(35)
  mr_turtle.right(135)
  mr_turtle.forward(75)
  mr_turtle.right(90)
  mr_turtle.forward(25)
  mr_turtle.end_fill()
  mr_turtle.penup()
  mr_turtle.left(90)
  mr_turtle.fillcolor("white")
  mr_turtle.begin_fill()
  mr_turtle.forward(50)
  mr_turtle.right(45)
  mr_turtle.forward(25)
  mr_turtle.right(45)
  mr_turtle.forward(25)
  mr_turtle.right(45)
  mr_turtle.forward(25)
  mr_turtle.right(45)
  mr_turtle.forward(100)
  mr_turtle.right(45)
  mr_turtle.forward(25)
  mr_turtle.right(45)
  mr_turtle.forward(25)
  mr_turtle.right(45)
  mr_turtle.forward(25)
  mr_turtle.right(45)
  mr_turtle.forward(50)
  mr_turtle.end_fill()
  mr_turtle.fillcolor("black")
  mr_turtle.left(90)
  mr_turtle.forward(20)
def xx1():
  mr_turtle.right(90)
  mr_turtle.forward(35)
  mr_turtle.right(90)
  mr_turtle.pendown()
  mr_turtle.forward(15)  
  mr_turtle.penup() 
def xx2():
  mr_turtle.left(90)
  mr_turtle.forward(40)
  mr_turtle.pendown()
  mr_turtle.forward(10)
  mr_turtle.right(90)
  mr_turtle.forward(10)
  mr_turtle.right(90)
  mr_turtle.forward(10)
  mr_turtle.left(90)
  mr_turtle.forward(10)
  mr_turtle.left(90)
  mr_turtle.forward(10)
def xx3():
  mr_turtle.penup()
  mr_turtle.right(90)
  mr_turtle.forward(30)
  mr_turtle.right(90)
  mr_turtle.forward(10)
  mr_turtle.left(180)
  mr_turtle.pendown()
  mr_turtle.forward(10)
  mr_turtle.right(90)
  mr_turtle.forward(10)
  mr_turtle.right(90)
  mr_turtle.forward(10)
  mr_turtle.left(180)
  mr_turtle.forward(10)
  mr_turtle.right(90)
  mr_turtle.forward(10)
  mr_turtle.right(90)
  mr_turtle.forward(10) 
def xx4():
  mr_turtle.penup()
  mr_turtle.forward(45)
  mr_turtle.left(90)
  mr_turtle.pendown()
  mr_turtle.forward(10)
  mr_turtle.left(90)
  mr_turtle.forward(10)
  mr_turtle.right(90)
  mr_turtle.forward(7)
  mr_turtle.right(180)
  mr_turtle.forward(17)
  mr_turtle.left(90)
def xx5():
  mr_turtle.penup()
  mr_turtle.forward(65)
  mr_turtle.pendown()
  mr_turtle.forward(10)
  mr_turtle.left(90)
  mr_turtle.forward(8)
  mr_turtle.left(90)
  mr_turtle.forward(10)
  mr_turtle.right(90)
  mr_turtle.forward(8)
  mr_turtle.right(90)
  mr_turtle.forward(10)
def xx6():
  mr_turtle.penup()
  mr_turtle.right(45)
  mr_turtle.forward(50)
  mr_turtle.left(45)
  mr_turtle.forward(3)
  mr_turtle.pendown()
  mr_turtle.forward(10)
  mr_turtle.left(90)
  mr_turtle.forward(20)
  mr_turtle.left(90)
  mr_turtle.forward(10)
  mr_turtle.left(90)
  mr_turtle.forward(10)
  mr_turtle.left(90)
  mr_turtle.forward(10)
def xx7():
  mr_turtle.penup()
  mr_turtle.right(87)
  mr_turtle.forward(55)
  mr_turtle.right(93)
  mr_turtle.pendown()
  mr_turtle.forward(10)
  mr_turtle.right(91)
  mr_turtle.forward(20)
def xx8():
  mr_turtle.penup()
  mr_turtle.left(140)
  mr_turtle.forward(55)
  mr_turtle.right(50)
  mr_turtle.forward(2)
  mr_turtle.pendown()
  mr_turtle.forward(10)
  mr_turtle.right(90)
  mr_turtle.forward(8)
  mr_turtle.right(90)
  mr_turtle.forward(10)
  mr_turtle.left(90)
  mr_turtle.forward(8)
  mr_turtle.left(90)
  mr_turtle.forward(10)
  mr_turtle.left(90)
  mr_turtle.forward(8)
  mr_turtle.left(90)
  mr_turtle.forward(10)
  mr_turtle.right(90)
  mr_turtle.forward(8)
  mr_turtle.penup()
  mr_turtle.right(135)
  mr_turtle.setpos(50.00,-35.00)
  mr_turtle.left(135)
def xxColor1():
  mr_turtle.setpos(50.00,-35.00)
  mr_turtle.forward(50)
  mr_turtle.right(90)
  mr_turtle.forward(10)
  mr_turtle.pendown()
  mr_turtle.fillcolor("red")      
  mr_turtle.begin_fill()
  for i in range(4):
    mr_turtle.forward(10)
    mr_turtle.right(90)
  mr_turtle.end_fill()
  mr_turtle.penup()
  mr_turtle.right(180)
  mr_turtle.forward(20)
  mr_turtle.left(90)
  mr_turtle.forward(50)
  mr_turtle.left(180)
  mr_turtle.fillcolor("black")
def xxColor2():
  mr_turtle.setpos(50.00,-35.00)
  mr_turtle.forward(40)
  mr_turtle.right(90)
  mr_turtle.forward(60)
  mr_turtle.pendown()
  mr_turtle.fillcolor("green")      
  mr_turtle.begin_fill()
  for i in range(4):
    mr_turtle.forward(10)
    mr_turtle.right(90)
  mr_turtle.end_fill()
  mr_turtle.penup()
  mr_turtle.right(180)
  mr_turtle.forward(60)
  mr_turtle.left(90)
  mr_turtle.forward(40)
  mr_turtle.left(180)
  mr_turtle.fillcolor("black")
def xxColor3():
  mr_turtle.setpos(50.00,-35.00)
  mr_turtle.right(180)
  mr_turtle.forward(18)
  mr_turtle.right(270)
  mr_turtle.forward(60)
  mr_turtle.pendown()
  mr_turtle.fillcolor("red")      
  mr_turtle.begin_fill()
  for i in range(4):
    mr_turtle.forward(10)
    mr_turtle.right(90)
  mr_turtle.end_fill()
  mr_turtle.penup()
  mr_turtle.right(180)
  mr_turtle.forward(20)
  mr_turtle.right(90)
  mr_turtle.fillcolor("black")
def xxColor4():
  mr_turtle.setpos(50.00,-35.00)
  mr_turtle.right(160)
  mr_turtle.forward(35)
  mr_turtle.left(70)
  mr_turtle.pendown()
  mr_turtle.fillcolor("green")
  mr_turtle.begin_fill()
  for i in range(4):
    mr_turtle.forward(10)
    mr_turtle.right(90)
  mr_turtle.end_fill()
  mr_turtle.penup()
  mr_turtle.left(90)
  mr_turtle.fillcolor("black")
def xxColor5():
  mr_turtle.setpos(50.00,-35.00)
  mr_turtle.left(170)
  mr_turtle.forward(35)
  mr_turtle.right(80)
  mr_turtle.pendown()
  mr_turtle.fillcolor("red")
  mr_turtle.begin_fill()
  for i in range(4):
    mr_turtle.forward(10)
    mr_turtle.left(90)
  mr_turtle.end_fill()
  mr_turtle.penup()
  mr_turtle.right(90)
  mr_turtle.fillcolor("black")
def xxColor6():
  mr_turtle.setpos(50.00,-35.00)
  mr_turtle.left(180)
  mr_turtle.forward(18)
  mr_turtle.left(270)
  mr_turtle.forward(60)
  mr_turtle.pendown()
  mr_turtle.fillcolor("green")      
  mr_turtle.begin_fill()
  for i in range(4):
    mr_turtle.forward(10)
    mr_turtle.left(90)
  mr_turtle.end_fill()
  mr_turtle.penup()
  mr_turtle.left(180)
  mr_turtle.forward(20)
  mr_turtle.left(90)
  mr_turtle.fillcolor("black")
def xxColor7():
  mr_turtle.setpos(50.00,-35.00)
  mr_turtle.forward(37)
  mr_turtle.left(90)
  mr_turtle.forward(62)
  mr_turtle.pendown()
  mr_turtle.fillcolor("red")      
  mr_turtle.begin_fill()
  for i in range(4):
    mr_turtle.forward(10)
    mr_turtle.left(90)
  mr_turtle.end_fill()
  mr_turtle.penup()
  mr_turtle.left(180)
  mr_turtle.forward(60)
  mr_turtle.right(90)
  mr_turtle.forward(40)
  mr_turtle.right(180)
  mr_turtle.fillcolor("black")
def xxColor8():  
  mr_turtle.setpos(50.00,-35.00)
  mr_turtle.forward(50)
  mr_turtle.left(90)
  mr_turtle.forward(10)
  mr_turtle.pendown()
  mr_turtle.fillcolor("green")      
  mr_turtle.begin_fill()
  for i in range(4):
    mr_turtle.forward(10)
    mr_turtle.left(90)
  mr_turtle.end_fill()
  mr_turtle.penup()
  mr_turtle.left(180)
  mr_turtle.forward(20)
  mr_turtle.right(90)
  mr_turtle.forward(50)
  mr_turtle.right(180)
  mr_turtle.fillcolor("black")
def yum1():
  mr_turtle.forward(50)
  mr_turtle.right(90)
  mr_turtle.forward(10)
  mr_turtle.pendown()
  mr_turtle.fillcolor("sandybrown")      
  mr_turtle.begin_fill()
  for i in range(4):
    mr_turtle.forward(10)
    mr_turtle.right(90)
  mr_turtle.end_fill()
  mr_turtle.penup()
  mr_turtle.right(180)
  mr_turtle.forward(20)
  mr_turtle.left(90)
  mr_turtle.forward(50)
  mr_turtle.left(180)
  mr_turtle.fillcolor("black")        
def yum2():
  mr_turtle.forward(40)
  mr_turtle.right(90)
  mr_turtle.forward(60)
  mr_turtle.pendown()
  mr_turtle.fillcolor("sandybrown")      
  mr_turtle.begin_fill()
  for i in range(4):
    mr_turtle.forward(10)
    mr_turtle.right(90)
  mr_turtle.end_fill()
  mr_turtle.penup()
  mr_turtle.right(180)
  mr_turtle.forward(60)
  mr_turtle.left(90)
  mr_turtle.forward(40)
  mr_turtle.left(180)
  mr_turtle.fillcolor("black")   
def yum3():
  mr_turtle.right(180)
  mr_turtle.forward(18)
  mr_turtle.right(270)
  mr_turtle.forward(60)
  mr_turtle.pendown()
  mr_turtle.fillcolor("sandybrown")      
  mr_turtle.begin_fill()
  for i in range(4):
    mr_turtle.forward(10)
    mr_turtle.right(90)
  mr_turtle.end_fill()
  mr_turtle.penup()
  mr_turtle.right(180)
  mr_turtle.forward(20)
  mr_turtle.right(90)
  mr_turtle.fillcolor("black")
def yum4():
  mr_turtle.right(160)
  mr_turtle.forward(35)
  mr_turtle.left(70)
  mr_turtle.pendown()
  mr_turtle.fillcolor("sandybrown")
  mr_turtle.begin_fill()
  for i in range(4):
    mr_turtle.forward(10)
    mr_turtle.right(90)
  mr_turtle.end_fill()
  mr_turtle.penup()
  mr_turtle.left(90)
  mr_turtle.fillcolor("black")
def yum5():
  mr_turtle.left(170)
  mr_turtle.forward(35)
  mr_turtle.right(80)
  mr_turtle.pendown()
  mr_turtle.fillcolor("sandybrown")
  mr_turtle.begin_fill()
  for i in range(4):
    mr_turtle.forward(10)
    mr_turtle.left(90)
  mr_turtle.end_fill()
  mr_turtle.penup()
  mr_turtle.right(90)
  mr_turtle.fillcolor("black")
def yum6():
  mr_turtle.left(180)
  mr_turtle.forward(18)
  mr_turtle.left(270)
  mr_turtle.forward(60)
  mr_turtle.pendown()
  mr_turtle.fillcolor("sandybrown")      
  mr_turtle.begin_fill()
  for i in range(4):
    mr_turtle.forward(10)
    mr_turtle.left(90)
  mr_turtle.end_fill()
  mr_turtle.penup()
  mr_turtle.left(180)
  mr_turtle.forward(20)
  mr_turtle.left(90)
  mr_turtle.fillcolor("black")
def yum7():
  mr_turtle.forward(37)
  mr_turtle.left(90)
  mr_turtle.forward(62)
  mr_turtle.pendown()
  mr_turtle.fillcolor("sandybrown")      
  mr_turtle.begin_fill()
  for i in range(4):
    mr_turtle.forward(10)
    mr_turtle.left(90)
  mr_turtle.end_fill()
  mr_turtle.penup()
  mr_turtle.left(180)
  mr_turtle.forward(60)
  mr_turtle.right(90)
  mr_turtle.forward(40)
  mr_turtle.right(180)
  mr_turtle.fillcolor("black")
def yum8():
  mr_turtle.forward(50)
  mr_turtle.left(90)
  mr_turtle.forward(10)
  mr_turtle.pendown()
  mr_turtle.fillcolor("sandybrown")      
  mr_turtle.begin_fill()
  for i in range(4):
    mr_turtle.forward(10)
    mr_turtle.left(90)
  mr_turtle.end_fill()
  mr_turtle.penup()
  mr_turtle.left(180)
  mr_turtle.forward(20)
  mr_turtle.right(90)
  
  mr_turtle.forward(50)
  mr_turtle.right(180)
  mr_turtle.fillcolor("black")


print('-----------------------------------------------------------\n')
print("Game App Idea: VIRTUAL ROSCA (powered by Python)\nCreated by: Daniel Pinto")
print('\n-----------------------------------------------------------')
print("\nTHIS GAME REQUIRES A TOTAL OF 8 PLAYERS")
input("\nPress ENTER in order to begin")
print('\n. . . . . . . . . . . . . . . . . . . . . . . . . . . . . .')
print("\nHear Ye, Hear Ye,\n\n   Today on January 6th " + str(currentYear) + ", we are gathered here to celebrate Día de los Reyes Magos with family and friends to find out who is hosting a fiesta next month on February 2nd featuring Tamales.\n\nLet's get ready to eat this virtual cake.\nWho will be the lucky winner? Hope you're hungry!")
square()
print('\nTIME TO CUT THE CAKE & PICK A SLICE')
print('\n. . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\n')

xx1()
xx2()
xx3()
xx4()
xx5()
xx6()
xx7()
xx8()
mr_turtle.speed(20)
xxColor1()
xxColor2()
xxColor3()
xxColor4()
xxColor5()
xxColor6()
xxColor7()
xxColor8()
mr_turtle.speed(1)

import random
dicts = {}
ri = random.randint(1,8)
mr_turtle.setpos(50.00,-35.00)
xx = ["1st", "2nd", "3rd", "4th", "5th", "6th", "7th", "8th"] 

for x in range(8):
  names = input("Name of " + xx[x] + " Cake Eater: ")
  try:
    chooseSlice = int(input("Which virtual slice looks good to you? (Please enter slice #1-8): "))
    if chooseSlice < 1 or chooseSlice > 8:
      print("\nERROR: Invalid entry")
      chooseSlice = int(input("Which virtual slice looks good to you? (enter NUMBERS only 1-8): "))
  except ValueError:
    print("\nERROR: Invalid entry  (no letters, numbers only)")
    chooseSlice = int(input("Which virtual slice looks good to you? (enter NUMBERS only 1-8): "))
  dicts[names.title()] = chooseSlice
  print('')
  print('')
  if chooseSlice == 1:
    yum1()
    mr_turtle.setpos(50.00,-35.00)
  if chooseSlice == 2:
    yum2()
    mr_turtle.setpos(50.00,-35.00)
  if chooseSlice == 3:
    yum3()
    mr_turtle.setpos(50.00,-35.00)
  if chooseSlice == 4:
    yum4()
    mr_turtle.setpos(50.00,-35.00)
  if chooseSlice == 5:
    yum5()
    mr_turtle.setpos(50.00,-35.00)
  if chooseSlice == 6:
    yum6()
    mr_turtle.setpos(50.00,-35.00)
  if chooseSlice == 7:
    yum7()
    mr_turtle.setpos(50.00,-35.00)
  if chooseSlice == 8:
    yum8()
    mr_turtle.setpos(50.00,-35.00)

print('<><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>\n')
print("LIST OF ALL PLAYERS WITH SLICE SELECTION")
print(list(dicts.items()))
print('\n<><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>\n')
input("\nTo see which slice baby Jesus is sleeping in,\nPRESS ENTER\n")
winner = list(dicts.keys())[list(dicts.values()).index(ri)]
print("CONGRATULATIONS " + winner + "! You get to host the annual Día de la Candelaria party with tamales on February 2nd.\nBaby Jesus was sleeping in slice #" + str(ri) + "\n ")
